# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ems' do
pod 'AFNetworking'
pod 'SDWebImage'
#pod 'MagicalRecord'
pod 'MBProgressHUD'
pod 'IHKeyboardAvoiding'
#pod 'DZNEmptyDataSet'
#pod 'ReactiveCocoa', '~> 2.5'
pod 'JSONKit-NoWarning'
#pod 'JSBadgeView'
#pod 'DateTools'
#pod 'Reachability'
#pod 'WYPopoverController'
#pod 'ActionSheetPicker-3.0'
#pod 'Masonry'
pod 'MJRefresh'
pod 'RBStoryboardLink'
end

